/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_HelloCJni */

#ifndef _Included_com_example_HelloCJni
#define _Included_com_example_HelloCJni
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_example_HelloCJni
 * Method:    getKey
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_HelloCJni_getKey (JNIEnv *, jclass);


#ifdef __cplusplus
}
#endif
#endif
